name = "kiraenterprisev5-3"
main = "src/index.js"
compatibility_date = "2024-09-18"
account_id = "2c48feaf73f0023e94ead812fcb5f01e"

[[d1_databases]]
binding = "DB"
database_name = "mykira"
database_id = "3a8ae3cc-0746-47c5-8a79-d77e695ccc16"
